export default {
    LIGHT: 'OpenSans-Light',
    REGULAR: 'OpenSans-Regular',
    SEMIBOLD: 'OpenSans-SemiBold',
    BOLD: 'OpenSans-Bold',
    CONDENSED: 'OpenSansCondensed-Bold',
    MONREGULAR: 'Montserrat-Regular',
    MONLIGHT: 'Montserrat-Light',
    MONSEMIBOLD: 'Montserrat-SemiBold',
    MONBOLD: 'Montserrat-Bold',
    MONMEDIUM: 'Montserrat-Medium',
    RUBREGULAR: 'Rubik-Regular',
    RUBLIGHT: 'Rubik-Light',
    RUBMEDIUM: 'Rubik-Medium',
};